"""slug field added to the Vendor table

Revision ID: 212dd553c62e
Revises: a68e603c25fa
Create Date: 2026-03-27 22:36:11.181174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212dd553c62e'
down_revision: Union[str, Sequence[str], None] = 'a68e603c25fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_token_blacklist'))
    )
    op.add_column('vendors', sa.Column('slug', sa.String(), nullable=False))
    op.create_index(op.f('ix_vendors_slug'), 'vendors', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_slug'), table_name='vendors')
    op.drop_column('vendors', 'slug')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
