"""add invites table

Revision ID: 6b20310df050
Revises: e4d588fa7c05
Create Date: 2026-03-30 08:22:10.811861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b20310df050'
down_revision: Union[str, Sequence[str], None] = 'e4d588fa7c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_groups_parent_id'), 'groups', 'groups', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_groups_parent_id'), 'groups', type_='foreignkey')
    op.drop_column('groups', 'parent_id')
    # ### end Alembic commands ###
