"""add sessions table

Revision ID: f8bfa3a6355c
Revises: 1da8b6e94089
Create Date: 2026-03-29 17:30:59.150306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8bfa3a6355c'
down_revision: Union[str, Sequence[str], None] = '1da8b6e94089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_sessions_refresh_jti'), 'sessions', type_='unique')
    op.create_index(op.f('ix_sessions_refresh_jti'), 'sessions', ['refresh_jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_refresh_jti'), table_name='sessions')
    op.create_unique_constraint(op.f('uq_sessions_refresh_jti'), 'sessions', ['refresh_jti'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
